### ISSUE TITLE
incrementCount($key, $options) param

### ISSUE THREAD

**Issue by od3n** [Team-Tea-Time/laravel-counter#4]
What is the possible value for $key?

In my case, I want to keep track my file download count

$download->incrementCount($key, $options);

**Comment by Riari** [comment]
The key can be any string you want to use to identify the count, so you might use `downloads` for example.

Then you can access the count like this: `$download->counts()->key('downloads')->first()`

By the way, I haven't updated this package for a while so there may be issues with the current Laravel version. Please do submit an issue or PR if you find anything wrong. Thanks!

**Comment by od3n** [comment]
@Riari alright, thank you
